on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build-java

jobs:
  build-java:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.java }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, java: '8' }
          - {os: ubuntu-latest, java: '11' }
          - {os: ubuntu-latest, java: '17' }

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.config.java }}

      - run: mvn -f ./other/pom.xml package
